constabulary/gb

- cmd/gb/main.go
- context.go
- gc.go
- package_test.go
Closes #26
Remove -goos and -goarch flags. They were not being honored and fixing them is quite complicated, so best to remove them for now.
> cmd/gb: remove support for -goos -goarch flags

- README.md
Just a minor change in the documentation for the -f flag, noting that it will disable incremental compilation.
> Clarify behavior of -f flag.

- getting-started.md
I actually went to see if `-q` was something different because it is used in the first example (stfp) but not in the second one (confd).
> Keeping it consistent

- cmd/gb/build.go
- cmd/gb/main.go
- cmd/gb/test.go
- log.go
Updates #47 
Before:
```
% gb build .../sftp
2015/05/07 21:20:56 INFO project root "/home/dfc/devel/demo"
2015/05/07 21:20:56 INFO compile github.com/kr/fs
2015/05/07 21:20:56 INFO compile golang.org/x/crypto/ssh
2015/05/07 21:20:56 INFO install /home/dfc/devel/demo/pkg/linux/amd64/github.com/kr/fs.a
2015/05/07 21:20:57 INFO install /home/dfc/devel/demo/pkg/linux/amd64/golang.org/x/crypto/ssh.a
2015/05/07 21:20:57 INFO compile github.com/pkg/sftp
2015/05/07 21:20:57 INFO install /home/dfc/devel/demo/pkg/linux/amd64/github.com/pkg/sftp.a
2015/05/07 21:20:57 INFO build duration: 1.823214205s map[compile:1.854594245s]
```
After:
```
% gb build .../sftp                                                                                                                         
```
This change …
> [RFC] reduce logging output in the default case

- build.go
- gb.go
- install.go
- log.go
Fixes #47 
Thanks for the feedback from #54, this change reduces the output in the success case even further
Before:
```
% gb build -f -R  ~/devel/demo6
```
After
```
% gb build -f -R  ~/devel/demo6
github.com/BurntSushi/toml
github.com/hashicorp/consul/api
github.com/kelseyhightower/confd/backends/env
github.com/coreos/go-etcd/etcd
github.com/garyburd/redigo/internal
github.com/samuel/go-zookeeper/zk
github.com/Sirupsen/logrus
github.com/kelseyhightower/memkv
github.com/garyburd/redigo/redis
github.com/kelseyhightower/confd/log
github.com/kelseyhightower/confd/backends/etcd
github.com/kelseyhightower/confd/backends/zookeeper
github.com/kelseyhightower/confd/integration/zookeeper
github.com/kelseyhightower/confd/backends/redis
github.com/kelseyhightower/confd/backends/consul …
```
> [RFC] Even less output at the default level

- build.go
- gb.go
Fixes #57
This PR changes the call to toolchain.Gc to invoke the compiler with its working directory set to `$PROJECT`.
To counter this, files passed to the compiler now include a path relative to `$PROJECT`. This results in error messages relative to `$PROJECT`.
lucky(~/devel/demo8/src/github.com) % gb build
github.com/fatih/color/broken
FATAL command "build" failed: [/home/dfc/go/pkg/tool/linux_amd64/6g -p github.com/fatih/color/broken -pack -o /tmp/gb120635804/github.com/fatih/color/broken.a -I /tmp/gb120635804 -I /home/dfc/devel/demo8/pkg/linux/amd64 -complete src/github.com/fatih/color/broken/color.go]: exit status 2
src/github.com/fatih/color/broken/color.go:27: non-octal character in escape sequence: b
Compare this to the output from the go tool
lucky(~/devel/demo8/src/github.com) …
> Always compile .go files related to $PROJECT

- context.go
Since we do not use real stack, it does not seem obvious for me to detect a cycle of length longer than 2.
> Add import cycle detection

- cmd/resolve.go
I ran across a problem today where I needed this info to understand why
gb wasn't building anything. Turns out it was a misvendored dependency.
> Include error

- cmd/cmd.go
- cmd/gb/test.go
- cmd/gotest.go
- cmd/resolve_test.go
- cmd/test.go
- cmd/test_test.go
- target.go
Fixes #102
The ability to build test packages has been moved out of gb, into gb/cmd.
This isn't the best name for the package, but it is consistent with keeping
as much of the shared gb/cmd/gb/ logic out of package main's.
> Test refactor

- gb.go
Hi,
during my hackish attempt of adding gb to [gin](https://github.com/codegangsta/gin), I noticed that the command output of the `runOut` method is only printed to stdout in the error case.
This means that information and output of the compiler and other commands can't be read by tools using gb by themselfs. This PR adds a simple error type that captures the original error, the command args and their output. 
Ps: see PR codegangsta/gin#73 if you want to play with it.
> runOut: don't lose command output to stdout

- .gitignore
- cmd/cmd.go
- cmd/gb/main.go
- cmd/gb/test.go
- cmd/test.go
- cmd/test_test.go
- cmd/testflag.go
- cmd/testflag_test.go
- testdata/src/testflags/testflags.go
- testdata/src/testflags/testflags_test.go
Implements support for passing arguments to the test binary. The
standard arguments, as well as arbitrary arguments.
This is not ready to merge, just want to make it available for review and comment.
Note: only argument parsing of ``-cover`` is implemented but I haven't done anything with building cover support into the test binary.
Also, when testing with ``gb test -v`` all debug output is shown. To only show verbose output, use ``gb test -q``
> WIP Test binary flag parsing

- cmd/gb-vendor/delete.go
- cmd/gb-vendor/update.go
- cmd/gb-vendor/vendor/manifest.go
Updates #126
I have added support for update and delete.
There are a lot of possible improvements (automatically detecting unused packages and deleting them with something like `gb vendor delete --unused`, or updating all dependencies `gb vendor update --all`, etc.). If you don't decline the PR (permanently) I will continue with adding other features.
Since the `gb vendor fetch` removes `.git` folder, it is required to remove old copy and clone new one.
I am open for improvements! :)
> Added support for update and delete in new gb-vendor

- cmd/gb/test.go
- cmd/testflag.go
- cmd/testflag_test.go
Last of the testflag stuff.
Copied the flag spec object from the [upstream testflag.go](https://github.com/golang/go/blob/master/src/cmd/go/testflag.go), this removes the need for looping through flag.FlagSet and cleans up the code and tests a bit.
Many more test cases were added.
> Improved testflag parsing

- cmd/gb-vendor/delete.go
- cmd/gb-vendor/fetch.go
- cmd/gb-vendor/main.go
- cmd/gb-vendor/update.go
- cmd/gb-vendor/vendor/manifest.go
- cmd/gb-vendor/vendor/repo.go
Updates #126 
Implements (only `gb vendor fetch` for now) #136
Fixes #137 
Added support for `--all`, `--branch`, `--revision` flag in `gb vendor fetch`.
Added support for `--all` flag in `gb vendor update`:
* I think `gb vendor update` should not have `--branch` and `--revision` flag, since it should get those from Manifest file and pull last revision of the branch specified in the Manifest file (explained in detail in  [#136](https://github.com/constabulary/gb/issues/136#issuecomment-105551838)).
Possible issue:
~~* after calling `gb vendor delete <package>`, package's parent directory stays empty~~ Fixed
**NOTES:**
* Checking out revision (commit sha) places git repository into Detached HEAD -> branch name becomes *HEAD* (also in manifest file)
> Support for --all, --branch, --revision in gb vendor fetch and --all in gb vendor update

- cmd/gb-vendor/list.go
Adds `gb vendor list`
```
% gb vendor list
github.com/kr/fs        https://github.com/kr/fs/       master  2788f0dbd16903de03cb8186e5c7d97b69ad387b
github.com/pkg/sftp/examples    https://github.com/pkg/sftp/examples    master  db7130eb6883678c3db453ba359e19306657528f
```
> cmd/gb-vendor: add gb vendor list subcommand

- gb.go
- gc.go
- install.go
This is a fix from the go tool which causes packages to be considered stale
if they are newer than the compiler that built them. This happens often if
using the trunk compiler
> gb: isStale returns true if compiler is newer than source

- cmd/cmd.go
- cmd/gb/main.go
- cmd/gb/plugin.go
Currently the command handling logic will interpret arguments to
all comamnds as import paths unless the name of the command is `plugin`,
then it won't.
Make this more flexible by removing the hard coded name and replacing it
with a function on the Command structure with a reasonable default.
> Add Command.ParseArgs

- cmd/cmd.go
- cmd/gb-vendor/list.go
- cmd/gb/doc.go
- cmd/gb/main.go
- cmd/gb/plugin.go
Fixes #74 
gb doc is a simple wrapper around go doc / godoc. Invocation is the same
gb doc $PACKAGE
gb doc $PACKAGE $SYMBOL
Without arguments gb doc behaves as if you had passed `gb doc .` which
expands to the current working directory.
> cmd/gb: add gb doc

- cmd/gb-vendor/main.go
- cmd/gb-vendor/update.go
This PR fixes 2 issues:
Issue 1:
```sh
$ gb vendor update
panic: runtime error: index out of range
goroutine 1 [running]:
main.main()
/.../constabulary/gb/cmd/gb-vendor/main.go:82 +0xb88
```
Issue 2: It shouldn't join the repository URL with the import path:
```sh
$ cat vendor/manifest
{
"version": 0,
"dependencies": [
{
"importpath": "github.com/constabulary/gb",
"repository": "https://github.com/constabulary/gb",
"revision": "119ad549aac0dcc74cc9d1dd48cd672be8d4b4aa",
"branch": "master",
"path": ""
}
]
}
$ gb vendor update -all
FATAL command "update" failed: could not determine repository for import "https:/github.com/constabulary/gb/github.com/constabulary/gb"
FATAL command "vendor" failed: exit status 1
```
> Fix a panic and a manifest update bug for gb vendor

- cmd/gb-vendor/main.go
- cmd/gb-vendor/vendor/discovery.go
- cmd/gb-vendor/vendor/imports.go
- cmd/gb-vendor/vendor/imports_test.go
- cmd/gb-vendor/vendor/repo.go
- cmd/gb-vendor/vendor/repo_test.go
Fixes #177 
Fixes #178 
This PR adds initial support to `gb vendor` for handling so called 'vanity' import paths.
Included are some regrettable tests which require network access, this is probably unavoidable without mocking out the http layer, so for the moment we'll live with it.
```
% gb vendor fetch golang.org/x/crypto/pbkdf2
Cloning into '/tmp/gb-vendor-402709523'...
remote: Total 1922 (delta 1207), reused 1922 (delta 1207)
Receiving objects: 100% (1922/1922), 1.42 MiB | 403.00 KiB/s, done.
Resolving deltas: 100% (1207/1207), done.
Checking connectivity... done.
copyfile(dst: /home/dfc/devel/juju/vendor/src/golang.org/x/crypto/pbkdf2/pbkdf2.go, src: /tmp/gb-vendor-402709523/pbkdf2/pbkdf2.go)
copyfile(dst: /home/dfc/devel/juju/vendor/src/golang.org/x/crypto/pbkdf2/pbkdf2_test.go, src: …
```
> cmd/gb-vendor: add support for vanity imports

- cmd/gb-vendor/fetch.go
- cmd/gb-vendor/main.go
- cmd/gb-vendor/update.go
- cmd/gb-vendor/vendor/_testdata/copyfile/a/rick
- cmd/gb-vendor/vendor/copy.go
- cmd/gb-vendor/vendor/copy_test.go
Fixes #184 
Ignore symlinks in the src directory.
Also mutes debugging output from `copyfile`
> cmd/gb-vendor: move copypath to vendor.Copypath, skip symlinks

- cmd/gb/build.go
When doing a failed build the temporary directories don't get removed.
> Clean up temporary files on build error

- cmd/gb-vendor/vendor/manifest_test.go
add "path" argument to assertNotExists and assertExists functions
> style(vendor): fix go vet format error

- cmd/gb-vendor/vendor/repo.go
- cmd/gb-vendor/vendor/repo_test.go
Fixes #203 
fix vendor fetch validimport regexp.
create test for package name length equal 1.
> fix,test(vendor): vendor fetch fail with pkg name length equal 1

- cmd/gb-vendor/alldocs.go
- cmd/gb-vendor/fetch.go
- cmd/gb-vendor/update.go
- cmd/gb-vendor/vendor/repo.go
Fixes #209
This PR adds support for fetching from a tag for all repos, however
tag is ignored by all but git. Hopefully someone with hg or bzr
skills can improve this.
This PR also adds a check to ensure that if a repo, again git, is fetched
from a tag or revision, that update will not let the caller update, as
there is no path from one revision to the next if you are in a detached
state.
The error message is very bad, but at least we don't promise something that
isn't possible.
```
% gb vendor fetch -tag r2015.06.03 gopkg.in/mgo.v2
% gb vendor update gopkg.in/mgo.v2
FATAL command "update" failed: cannot checkout HEAD
FATAL command "vendor" failed: exit status 1
```
> gb-vendor: add support for fetching a tag

- cmd/gb-vendor/alldocs.go
- cmd/gb-vendor/fetch.go
- cmd/gb-vendor/update.go
- cmd/gb-vendor/vendor/repo.go
- cmd/gb-vendor/vendor/repo_test.go
Fixes #207
Adds support for optional fetching via insecure paths.
`gb fetch` / `update` have a new flag, `--precaire` which enables discovery of insecure repos. It defaults to off.
No support for insecure bzr, I'll wait for someone to request it.
Currently `git://` scheme is considered insecure as, while it has no support for pushing, there is no transport security so could be used in a man-in-the-middle attempt.
Who cares enough to debate this ?
> Support for optional fetching via insecure paths

- cmd/gb-vendor/vendor/imports.go
- cmd/gb-vendor/vendor/imports_test.go
- cmd/gb-vendor/vendor/repo.go
The missing piece
% gb vendor fetch dave.cheney.net/baz
skipping insecure protocol: http://dave.cheney.net/baz?go-get=1
FATAL command "fetch" failed: unable to determine remote metadata protocol
FATAL command "vendor" failed: exit status 1
> cmd/gb-vendor/vendor: add support for insecure metadata retrieval

- cmd/gb-vendor/alldocs.go
- cmd/gb-vendor/update.go
- Fixed typos in several place were the word dependency was misspelled.
- Add `-precaire` option to the places of the documentation where it was
missing.
> Fix typos and missed option

- build.go
- cmd/gb/build.go
- cmd/gb/main.go
- context.go
- gb.go
- gc14.go
- gc15.go
Fixes #240
Sample usage:
gb build -gcflags=-m
> cmd/gb: add -gcflags to build flags

- cmd/depset.go
- cmd/gb-vendor/alldocs.go
- cmd/gb-vendor/fetch.go
- cmd/gb-vendor/update.go
- cmd/gb/depset.go
- cmd/gb/stringset.go
- cmd/gb/stringset_test.go
depset is an experimental command to explore analysing dependency sets.
It produces output like this, http://paste.ubuntu.com/11739677/
At the moment it has worse than quadratic behaviour, making it unsuitable for anything serious.
The goal of depset is to develop a set of functions in the `cmd` package that can be used by tools like `gb-vendor` to analyse dependencies as a set rather than as individual imports.
Dependency sets are groups of packages that are related by being children of a single source root. A canonical example of a source root is $GOPATH/src, another is $PROJECT/src. However we can be smarter and create sets for each vendored import tree, which in turn allows us to determine which dependencies are no longer referenced with more accuracy than the current gb vendor purge …
> cmd/gb: add experimental depset command and add recursive fetch ability

- cmd/gb-vendor/fetch.go
Fixes #246 
Changing -no-recurse flag to simply be called -recurse given that the default behavior is to fetch recursively unless explicitly disabled.
> Updated fetch.go to correct a typo in the -no-recurse flag

- cmd/gb-vendor/list.go
Hey,
I piped the output from `gb vendor list` through `text/tabwriter` to make it more readable. I can hide it behind a flag if preferred.
Before:
After:
> gb vendor list: use tabwriter to format output

- cmd/gb-vendor/vendor/repo.go
git 1.7.1 (Used by RHEL 6) does not have the --exit-code option
so gb vendor fetch fails, this changes the test to do a simple
check for the string "HEAD" in the output instead.
> Check output instead of exit status for git ls-remote

- cmd/gb-vendor/main.go
My instinct after go get'ing stuff is to run '-help' on all the binaries that appeared that I didn't expect. In the case of gb-vendor, that resulted in some confusing output about 'project root'. 
I would have found the usage text much more useful as it starts with 'gb vendor', immediately suggesting that gb-vendor is run by the gb command and shouldn't be run by hand.
This patch is purely cosmetic.
> slightly improved output when running gb-vendor directly

- cmd/gb-vendor/vendor/repo.go
Describe remote repos with url.URLs rather than strings.
> cmd/gb-vendor/vendor: use urls instead of strings

- cmd/gb/alldocs.go
- cmd/gb/info.go
Fixes #267
This PR adds a new subcommand, `info`. This returns some (hopefully) pertinent
information about the project, and an error code to indicate if the path is part
of a gb project or not.
zapf(~/devel/demo4) % gb info
GB_PROJECT_DIR="/Users/dfc/devel/demo4"
GB_SRC_PATH="/Users/dfc/devel/demo4/src:/Users/dfc/devel/demo4/vendor/src"
zapf(~/devel/demo4) % echo $?
0
zapf(~/devel/demo9) % gb info
FATAL could not locate project root: could not find project root in "/Users/dfc/devel/demo9" or its parents
zapf(~/devel/demo9) % echo $?                                                                         
1
> cmd/gb: add gb info subcommand

- cmd/gb/main.go
- cmd/resolve_test.go
- context.go
- example_test.go
- package_test.go
- project.go
Fixes #268
This PR adds a feature request from GopherCon to allow users with, uh, unique,
project layouts to construct them manually. The layout that was previously fixed
in `NewProject`, is now moved to `cmd/gb`.
`cmd/gb` will always mandate the traditional `$PROJECT/src`, `$PROJECT/vendor/src` pair, but
users can fork `cmd/gb` and build their own tool if they need more control.
> gb: NewProject now takes SourceDir options

- build.go
- build_test.go
- install.go
- install_test.go
Fixes #294 
This PR allows gb to consider main packages cacheable. Additionally the linking step is only performed if the main package is stale. The net result is running `gb build all` a second time should compile nothing.
TODO:
> Initial support for caching main packages

- cmd/gb/plugin.go
Hi,
On a fresh host (go 1.5): 
$ go get github.com/constabulary/gb/...
Before fix:
$ gb plugin
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
main.glob.func5(0xc82011a2a0, 0xc82000a2f0, 0x0, 0x0, 0x0, 0x0)
/home/proullon/work/src/github.com/constabulary/gb/cmd/gb/plugin.go:61 +0x174
main.main()
/home/proullon/work/src/github.com/constabulary/gb/cmd/gb/main.go:66 +0x4a8
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
After fix: 
$ gb plugin
FATAL command "plugin" failed: plugin: unable to locate "gb-plugin": exec: "gb-plugin": executable file not found in $PATH
> fix (gb plugin): avoid panic when no argument is provided

- cmd/gb/main.go
Update #319 
This PR adds a check to attempt to diagnose gb failures due to a mismatch between the version of Go that compiled gb, and the version of Go that exists on the machine when gb is invoked.
I expect it will cause some false positives, and if so, we'll address them or remove the check.
```
% gb build
FATAL Go version does not match: gb was compiled with "devel +fa87cf8 Wed Aug 19 04:36:55 2015 +0000", installed Go version from /home/dfc/go is "devel +8ca7856 Sat Aug 22 18:39:29 2015 +0000"
```
> cmd/gb: verify the Go install has not changed

- context.go
- context_test.go
- package.go
It's a horrible name, I couldn't think of a better one.
ctxString represents a hyphen seperated string of identifying
properties of the Context. GOOS and GOARCH are the key ones, but
others like -tags, -race, -nocgo, etc may be present.
Not supported yet, but if present, additional context elements must
be sorted aphabetically.
> Introduce ctxString

- cgo.go
Updates #331 (doesn't fix it, just makes it blow up less)
> cgo: do not pass cgoLDFLAGS to cmd/cgo directly

- cmd/gb/main.go
- cmd/gb/plugin.go
Fixes #318
- Replace plugin with help text, plugin is not a "runnable" command
- Hard wire plugin behavior inside main.go
> cmd/gb: finally fix plugin handling

- build.go
- build_test.go
- cmd/cmd.go
- cmd/env.go
- cmd/gb-vendor/fetch.go
- cmd/gb-vendor/main.go
- cmd/gb/list.go
- cmd/gb/main.go
- cmd/gotest.go
- cmd/path.go
- cmd/resolve.go
- cmd/test.go
- cmd/test_test.go
- context.go
- gb.go
- gc.go
- log/log.go
- vendor/imports.go
- vendor/repo.go
Refactor logging
- move log functions into their own package, `log`. Hopefully one day in the future this can be outsourced. 
- Logging is now more opinionated, there are only three levels and three corresponding log commands, `Debugf`, `Infof` and `Fataf`. `Verbose` enables debug level, `Quiet` silences info level, that's all there is too it. Errors, if not fatal should be handled and printed at info level -- they were not fatal after all.
> Refactor logging

- cmd/gb/info.go
- context.go
Fixes #366
```
% gb info
GB_PROJECT_DIR="/Users/dfc"
GB_SRC_PATH="/Users/dfc/src:/Users/dfc/vendor/src"
GB_PKG_DIR="/Users/dfc/pkg/darwin-amd64"
GB_BIN_SUFFIX="-darwin-amd64"
```
> cmd/gb: gb info report pkg path and bin suffix

- cmd/gb/main.go
`gb test` failed leak working directory.
`log.Fatal` call `os.Eixt`. deferred functions are not run.
> Fix: Clean working directory

- build_test.go
- cgo.go
- cmd/gb/main.go
- context.go
- gc.go
- package_test.go
- testdata/src/nested/a/a.go
- testdata/src/nested/b/b.go
Fixes #372
Updates #331 
Use a unique temporary directory for cgo build files.
> cgo: use unique directory for build

- cmd/testflag.go
- cmd/testflag_test.go
The gb test command advertises support for all valid
flags to gb build (e.g. -P), but the logic which determines which flags
should be sent to the test binary was not aware of them and blithely
passed them through. Add all valid build flags to the map indicating
they are meant for gb and not to passed through.
Note: It seems like the best long-term solution to this problem would be for the caller to pass through its `flag.FlagSet` and modify `TestFlagsExtraParse` to walk it with `VisitAll`. This would avoid the necessity of update two different locations (in two different packages!) in the code when adding a new flag to `gb test`.
> Avoid passing build flags to test process.

- build.go
- cmd/test_test.go
- package.go
- package_test.go
- testdata/src/main/main.go
Fixes #375
The test for Package.isMain had a loophole where a main package,
being built as a test would be linked.
> test: do not build a main package called main in test scope

- cgo.go
- wercker.yml
The Go 1.4 build atrophied when wercker upgraded to Go 1.5.
> Pin wercker to go 1.4.2 (box v1.3.3)

- wercker.yml
See https://github.com/constabulary/integration-tests/pull/1 for details. :+1:
(This totally enables both `go-sdl2` and `service.v1`! :metal:)
> Update wercker.yml to use "box: golang" and use the updated integration-tests to simplify test running

- package_test.go
Fixes:
```
--- FAIL: TestPackageBinfile (0.00s)
package_test.go:56: (b).Binfile(): want C:\gopath\src\github.com\constabulary\gb\testdata\bin\b, got C:\gopath\src\github.com\constabulary\gb\testdata\bin\b.exe
```
Not sure if this is the right fix, but I'll let you judge me on that. :smile:
> Add ".exe" to the TestPackageBinfile test for windows binaries

- wercker.yml
https://github.com/docker-library/official-images/pull/1060 is merged, built, and pushed, so this explicit `g++` installation is no longer necessary :smile:
> Remove temporary "g++" hack from "wercker.yml"

- appveyor.yml
See https://ci.appveyor.com/project/tianon/gb for where I've got this setup on my fork.  I've managed to get the build down to ~2m. :smile:
If you like what you see, setting up AppVeyor should be as simple as creating an account, authorizing them for GitHub, and adding "constabulary/gb" as a project.  I'd also recommend turning on the "ignore branches without `appveyor.yml`" setting, but none of the other settings should be necessary (since they're mostly specified here and having an `appveyor.yml` overrides the entire UI settings anyhow).
I _think_ we can get the integration tests running here too, but that'll take a little more refactoring over in the other repo (especially the `setup.bash` files).
> Add initial appveyor.yml

- cmd/gb/alldocs.go
- cmd/gb/build.go
- cmd/gb/doc.go
- cmd/gb/env.go
- cmd/gb/generate.go
- cmd/gb/list.go
- cmd/gb/test.go
I noticed that the usage line for `list` showed a few flags that weren't explained. While adding those explanations, I also made line wrapping for some help output that had bugged me on narrower terminals (`build`) consistent with other commands that were nice and pretty, and generally tried to make all the source formatting consistent.
I'm new to gb and just started browsing the source, so there may be some discrepancies I've missed fixing (not sure yet if all the `build` flags are correctly documented), but I think this is a good start.
> Doc tidying: add missing flag docs for list command, line wrapping

- gc.go
- gc_test.go
Do not change directory before invoking the gc tool. Instead,
relativize each filepath passed to the gc tool to the current
working directory. This greatly improves error messages produced
by gc since the broken file is now identified by an unambiguous
path.
The testing infrastructure required for this involves introducing
a new runOut variable to gcToolchain so it can be mocked. A similar
run variable is also introduced for parity of implementation and
possible future tests.
Fixes https://github.com/constabulary/gb/issues/341
> Pass workingdir-relative paths to gc to improve error messages

- build_test.go
- cmd/gb/alldocs.go
- cmd/gb/build.go
- cmd/gb/info.go
- cmd/gb/main.go
- context.go
- context_test.go
- gb.go
- package.go
- testdata/src/tags1/t.go
- testdata/src/tags2/t.go
Add support for build tags. Build tags modify the package resolution logic, a la build constraints, build tags also affect staleness computation.
Packages built with tags in effect will be stored in their own package cache. Binaries built with with tags in effect will have the tags appended as a suffix.
Fixes #81
> cmd/gb: add build tags

- build.go
- context.go
- package.go
Fixes #323
Forcing every package to have an explicit dependency on the runtime package,
even though 99% of the time they would have a transitive dependency was lame.
It also added many edges to the action graph that were not necessary.
However, the _implicit_ runtime dependency is actually a _link time_ depdendency
not a compile time dependency; pkg runtime must be up to date for the link phase
to run, compilation without linking is not affected.
Realising this we can add the runtime as a depdendency of all _main_ packages,
which reduces the number of redundant edges signficantly.
This also makes it possible to add additional link time depdendencies later, like
math, or runtime/race as required.
> Do not force every package to depend on runtime explicitly

- cmd/gb/build.go
- cmd/gb/list.go
- cmd/gb/path.go
- cmd/gb/path_test.go
- cmd/gb/resolve.go
- cmd/gb/resolve_test.go
- cmd/gb/test.go
- cmd/gb/testflag.go
- cmd/gb/testflag_test.go
- cmd/path.go
- test/gotest.go
- test/test.go
- test/test_test.go
The goal of not placing the test code directly in gb/ was to demonstrate
that testing did not require tight coupling with gb/ itself -- and this is
true, placing the test code outside gb/ has demonstrated that testing is
a unique function.
However, placing test code inside gb/cmd was a poor choice, and the lesser
evil would be to create yet another package and place the test support code
in that, which is what this PR does.
In the future several things will probably happen.
1. The test code may be integrated into gb/ proper, this would probably be a
net win for the surface area of the greater gb library.
2. The code in gb/cmd will be reduced or eliminated.
> new package: gb/test

- gc.go
This commit updates `gb` to automatically modify error paths in a command's output to be relative to the user's working directory, enabling the use of tools like Vim's quickfix to help navigate errors. Before, it would output directory information on individual lines, and the line containing the error would mean nothing to an editor since it would only be the file's base name, but with this patch, `gb` error output is now easily and correctly parsed by editors.
This is a very simple change tailored to my specific use case, and there are probably some changes that could be made to have it integrate better with the rest of `gb`, but it works, and is very straightforward in its functionality.
> Modify error paths to be relative to the working directory

- context.go
- resolve.go
- resolve_test.go
Remove the Srcdirs method from the resolver interface, making Resolver
a single method interface.
> gb.Resolver interface, remove Srcdirs

- cmd/gb/test.go
- test/test.go
* gb test now removes the _test/testmain file immediately after executing to
reclaim space faster.
* build all dependencies immediately, but arrange for linking _test/testmain
to occur sequentially with execution, so that linking and execution are run
in the same executor, this prevents multiple testmains being built on disk
before being run.
> gb/test: scale test improvements

- cmd/gb-vendor/main.go
- cmd/gb/main.go
- context.go
- gb.go
- log/log.go
Fatalf is unnecessary, and should not be called from anywhere but
the top level of the application.
> log: remove Fatalf

- cgo.go
- context.go
- gc.go
Fixes #440
Prior to #437 the name of the package under compile or test would be
printed *before* the operation started. This was a problem, because the
compilation output could occur later, and not line up with the package
name.
After #437, package name output was surpressed until the compile/test
action completed successfully. This helped improve the output for tests
but as the overall action, the print would never occur, only the output
to stdout from the child process.
This PR solves the problem at the source by delegating the responsibility
for printing the name of the package before any child output. If all
actions complete, then the final action in the set will print the name
of the package.
As it is now unused, `context.run` has been removed.
TODO:
> Always capture command output and report package name

- build.go
- cgo.go
- cmd/gb-vendor/fetch.go
- cmd/gb/main.go
- gc.go
- log/log.go
- test/test.go
- vendor/repo.go
The uses of gb/log are so simple now that there is no value in having
a log.Info wrapper around fmt.
At the same time, address the remaining TODO items on #442.
go tools observed behaviour.
Finally, remove log.Quiet flag as there is no ERROR level, nor INFO level.
gb users should pipe the appropriate fd's to /dev/null to adjust the
verbosity level of cmd/gb.
> log: remove Infof

- build.go
- build_test.go
- cmd/cmd.go
- cmd/gb-vendor/main.go
- cmd/gb/main.go
- context.go
- debug/debug.go
- gb.go
- test/gotest.go
- test/test.go
- test/test_test.go
This PR adds basic support for improved debugging support.
- gb/log was renamed to gb/debug to reflect the fact it is only involved in debug logging.
- the `-v` flag is removed from cmd/gb, info logging is controlled by piping stdout to /dev/null.
- debug support now lists file and line numbers, packages are elided.
- DEBUG takes a regex, but the regex is ignored, any non empty value will enable debugging unconditionally.
> debug: debug logging refactoring

- cmd/gb-vendor/main.go
- cmd/gb/main.go
I don't have much familiarity with gb internals, but I use it a lot and saw the "Help Wanted" sign.  This PR may not be exactly what you're looking for. I couldn't come up with a good reason why args < 1 should cause an error at the gb level... why not let the plugins worry about that?  Also, the various exit codes in gb-vendor were causing ugly "FATAL: ..." at the end of the help, so I pulled them.
Fixes #446
> Show vendor plugin help when no command is given

- .travis.yml
- vendor/repo.go
- vendor/repo_test.go
Fixes #452
Because of reasons bitbucket.org is not in the ssh known hosts' file in tavis.yml. This leaves two questions
1. why does it appear to be in the ssh hosts' file on the other CI providers
2. why, even though we assign /dev/null to Stdin, does mercurial still prompt for an answer
Having no good answer for both, try to work around the problem by pre-populating the known hosts file during setup.
> vendor: reactivate bitbucket tests

- build.go
- cmd/gb/build.go
- cmd/gb/main.go
- cmd/gb/signal.go
- cmd/gb/signal_notunix.go
- cmd/gb/signal_unix.go
- cmd/gb/test.go
- executor.go
- executor_test.go
This is the logic that Alex Brainman and I added to cmd/go back in Go 1.0. It's not perfect, but it's worked well enough for the last few years.
Fixes #436
Updates #445
> cmd/gb: catch signals during build and test

- test/test.go
- test/test_test.go
Update #448
The previous method of destructuring actions into multiple nested
anon functions was cute, but overcomplicated. It might also have
been wrong, and was causing #448.
> gb/test: refactor execution of test binary

- build.go
- cgo.go
this is based on: 
[golang/go/src/cmd/go/build.go#L1487-L1490](https://github.com/golang/go/blob/21efa7b2bc872958bcb252f5ab4dc52b2b0abeae/src/cmd/go/build.go#L1487-L1490)
[golang/go/src/cmd/go/build.go#L3056](https://github.com/golang/go/blob/21efa7b2bc872958bcb252f5ab4dc52b2b0abeae/src/cmd/go/build.go#L3056)
My use case was embedding the resource file inside cross compiled .exe without cgo
using: rsrc tool: [akavel/rsrc](https://github.com/akavel/rsrc)
or windres: lxn/walk#108
and it worked, I'm not sure how to write the test for this or if the cgo related changes are correct. 
Please advice, Thanks.
> build: add support for .syso files

- cmd/gb/testflag.go
- cmd/gb/testflag_test.go
> gb/cmd/gb: gb test now accepts -tags=a,b,c

- cmd/gb/alldocs.go
- cmd/gb/info.go
- cmd/gb/plugin.go
Fixes #393
Fixes #394 
Add `GB_GOROOT` value to report the `GOROOT` that build this gb.
> cmd/gb: gb info reports GOROOT that build gb

- cmd/gb/alldocs.go
- cmd/gb/test.go
- cmd/gb/testflag.go
- cmd/gb/testflag_test.go
- context.go
- test/test.go
> cmd/gb: gb test -v enables verbose test output

- cmd/gb/alldocs.go
- cmd/gb/env.go
- cmd/gb/gb_test.go
- cmd/gb/info.go
`gb info` optionally accepts a list of environment variable names and
returns their values. `gb env` is aliased to gb info.
Updates #476
> cmd/gb: info and env returns values for env vars

- cmd/gb/alldocs.go
- cmd/gb/gb_test.go
- cmd/gb/test.go
- cmd/gb/testflag.go
- cmd/gb/testflag_test.go
Fixes #473
Handling of flags that are parsed by both gb and a sub process is tricky.
So that the arguments are not parsed as package parameters by gb test
we move them to the front of the argument list when parsed by gb, but
leave them at the end of the list for the test binary to parse after
invocation.
> cmd/gb: fix parsing of passToAll test arguments

- cmd/gb/gb_test.go
- cmd/import.go
- cmd/path.go
- vendor/imports_test.go
Fixes #481
Fixes #422
Update #157
Update #308
Following symlinks was added in 7597be71. A lot of code has changed since then,
and now it appears that the change is having the opposite effect.
Revert the change to cmd/import.go and add tests to assert that #157 and #481 work.
> cmd: remove symlink evaulation during root discovery

- context.go
- context_test.go
Updates #96
Adds option to configure the context for a race build. This enables the
`race` build tag, and sets `Context.race`.
Also adds some tests to prove this stuff basically works.
> Add WithRace Context option

- cmd/cmd.go
- cmd/gb/doc.go
- cmd/gb/env.go
- cmd/gb/info.go
- cmd/gb/main.go
- vendor/imports_test.go
ParseArgs required a context before it could be called, but it was
never used. In all cases ParseArgs was being used to skip treating
arguments as packages (or package globs).
> cmd: remove Command.ParseArgs

- cmd/gb/build.go
- cmd/gb/gb_test.go
- cmd/gb/main.go
- cmd/gb/testflag.go
- cmd/gb/testflag_test.go
Wire up -race to gb build and gb test.
Update #96
> cmd/gb: wire up -race flag

- build.go
- build_test.go
- cmd/gb/gb_test.go
- context.go
- context_test.go
- package_test.go
- stdlib.go
Fixes #96
Adds the race detector you all know and love to gb.
Todo:
> Add race detector support

- vendor/repo.go
- vendor/repo_test.go
Prior to this PR, attempting to run `gb vendor fetch goji.io` would error out with a "not a valid import path" error.  This was unexpected since `go get goji.io` works fine.
> Fix `gb vendor fetch goji.io`

- cmd/gb/gb_test.go
- cmd/gb/main.go
Fixes #494
Upate #96
If race support is missing, refuse to try to build, and give link to faq to help people install the race runtime.
> cmd/gb: refuse to run if -race support missing

- cgo.go
- gb14.go
- gb15.go
- gc.go
- goversion12.go
- goversion13.go
- goversion14.go
- goversion15.go
- goversion16.go
Previously we had two constants, go14 and go15, but adding a third, go16 makes
it clear that the design is wrong.
Replace this with one constant, `goversion` which can be compared with other
constants literals at compile time. eg, `if goversion > 1.4 { // go 1.5 and later }`.
> Refactor goversion support

- build.go
- install.go
- install_test.go
`installpath` always returns the path to install a `.a` file into `$PROJECT/pkg/$tag`.
We also remove `pkgdir`, and roll it into `pkgfile` as there is now only one caller.
A future PR will refactor `pkgfile` to return the location of a previously
compiled `.a` file.
> Introduce installpath

- install.go
- install_test.go
`pkgpath` always returns the location where a previously compiled `.a` for this
package would be found. `pkgpath` considers elements of the context like tags
cross compilation and race status.
`pkgpath` is used exclusively by `isStale` to determine if the package is up to date.
However, `pkgpath` is _not_ used to compute the target to install a `.a` file. This
discontinuity takes into account the fact that if the stdlib is missing for a
particular build context, replacement files should be written to `installpath`,
the `$PROJECT/pkg/` directory.
> Refactor pkgfile to become pkgpath

- cgo.go
- gc.go
Hiya,
This fix works for me under the above conditions.  Not sure if this introduces regressions in other environments, but I feel "It Should Work".
The extld was removed via commit de34371c9f25bef9e9b6fdb45d653022738ef6fd, not sure why, probably gcc() disappeared?
Derek
> fix for #506, adding extld back into Ld()

- cgo.go
- cmd/gb/doc.go
- cmd/gb/generate.go
- gc.go
- test/test_test.go
gb.Context.Context is going away, it will be replaced by a rewritten
importer package. This PR is an intermediary step which simplifies the
interface to build.Context.Import.
> remove use of context.GOROOT

- install.go
Fixes #515
In the 0.3.x series we removed the hard coded list of packages to assume
are up to date and let that fall through to `isStale`. This worked ok, except
the Go installer for Darwin is broken and its timestamps are not correct.
Work around this by assuming that _iff_ the package is the standard lib and
_iff_ we are not cross compiling, then the standard lib is up to date. This
mimicks the pre 0.3.x behaviour and avoids the problem with broken timestamps
in the darwin binary installer.
> Always assume the stdlib is up to date if present

- context.go
- context_test.go
- install.go
Remove `Context.Context`, in preparation for the new importer.
> Remove build context

- cmd/gb/gb_test.go
- cmd/gb/generate.go
Update #521
Also add simple test for go generate.
> cmd/gb: fix search path for `go generate`

- cmd/gb/doc.go
- cmd/gb/gb_test.go
Update #521
Also add simple test for gb doc.
> cmd/gb: fix search path for 'gb doc'

- cmd/gb/gb_test.go
Fixes #521
Try to locate `bin/go` in the various permutations that package managers use.
> cmd/gb: handle various go installation permutations

- cmd/gb/gb_test.go
- package.go
Fixes #346 
Especially when cross compiling, it would be useful to have the binary names in a standard format. Here are some samples:
```
$ tree                                                                                                                                                                
.
└── src
└── hi
└── main.go
2 directories, 1 file
$ gb build -f                                                                                                                                                         
hi
$ tree                                                                                                                                                                
.
├── bin
│   └── hi
├── pkg
│   └── linux-amd64
│       └── hi.a
└── src
└── hi
└── main.go
5 …
```
> Allow GOOS and GOARCH control the binary name format

- vendor/repo.go
~ is an allowed character in the import path, and it's used in the wild for user repositories
> vendor: allow ~ in import path

- depfile/depfile.go
- depfile/depfile_test.go
This package parses an io.Reader consisting of key/value pairs into a `map[string]map[string]string`. The format of the line is
name key=value [key=value]...
The intention is this package will be used to parse a dependency file, or `depfile`, consisting of lines like this
```
github.com/pkg/profile version=0.1.0
github.com/docker/docker version=1.7.0
```
_note:_ this package does not assign semantic meaning to the contents of the `map[string]map[string]string`.
> new package: depfile

- cmd/gb/generate.go
`gb generate` does not work on Windows without this change.
> Use cross-platform list seperator when constructing GOPATH for go generate.

- action_test.go
- build.go
- context.go
- install.go
- package.go
Previously `gb.Package.Imports` was a method which would fetch packages'
from the context package cache matching the import paths of
`gb.Package.Package.Imports`.
This change causes the fetch to happen earlier, which will avoid the
panic happening before the build starts. A followup change can now
change the panic to be an error.
> Memoize Package.Imports

- cmd/gb/build.go
- cmd/gb/gb_test.go
- context.go
Fixes #505
Refactoring the importer and package root resolution broke a
supported, or promised (I cannot find the link) mode of operation.
See https://github.com/constabulary/gb/pull/548#issuecomment-172972528
This change restores the ability to build packages from $PROJECT/vendor/src
providing they are named explicitly, globbing is not supported.
> Fix package resolution (again)

- cmd/gb/gb_test.go
Fixes #571
Without this, ARM (armv5, armv7, arm64, and really any `GOARCH` that isn't supported with `GOOS=windows`) fail in the following way:
```
--- FAIL: TestCrossCompile (0.92s)
gb_test.go:179: running /tmp/testgb935828407/testgb [build]
gb_test.go:193: standard error:
gb_test.go:194: # runtime
netpoll_windows.go:18: undefined: overlapped
FATAL: command "build" failed: exit status 2
gb_test.go:203: gb [build] failed unexpectedly: exit status 1
```
> Allow TestCrossCompile to work on ARM* by setting explicit GOARCH too

- cmd/gb-vendor/fetch.go
The branch indication was being carried on to the recursive dependencies
because the global branch variable was getting shadowed before being
cleared.
Reported in FiloSottile/gvt#25
> gb-vendor: fix recursive dependency fetching with -branch

- cmd/gb/alldocs.go
- cmd/gb/gb_test.go
- cmd/gb/test.go
- cmd/gb/testflag.go
- context.go
- test/test.go
Nope mode, a global flag on gb.Context allows gb test to hook `-n` to
skip executing tests, just build and link them.
> Feature: nope mode

- cmd/gb-vendor/restore.go
- cmd/gb-vendor/update.go
If I use my private repository at github as dependency in my project, when I try to do `gb restore` or `gb update`, gb ignores my schema, and by default uses https and this breaks my build process on CI, because git asks to input a username and a password for https and I can't automatically answer on these questions in the build script.
This PR solves the issue
> Fix problem with private repositories

- cmd/gb/gb_test.go
See "cmd/gb/main.go" from ~line 138 through ~line 152:
139: fatalf("race detector not supported on %s/%s", runtime.GOOS, runtime.GOARCH)
145: fatalf("race detector not supported on %s/%s", runtime.GOOS, runtime.GOARCH)
151: fatalf("go installation at %s is missing race support. See https://getgb.io/faq/#missing-race-support", runtime.GOROOT())
Fixes #567
> Update TestRaceMissing to support all the potential error messages of "race not supported"

- cmd/gb/gb_test.go
- cmd/gb/testflag.go
- cmd/gb/testflag_test.go
Fixes #605
Goconvey, and probably others, do not parse flags, they just string
match against `os.Args`. Because of this the semantically identical,
`-test.v` and `-test.v=true` are not identical. Fix this by expanding
boolean arguments that are passed to the test subprocess.
> cmd/gb: expand boolean flags when passed to test subprocess

- cmd/gb/gb_test.go
- cmd/gb/main.go
Restore the "all" alias for matching packages. This was never advertised
but apparently people are using it[1], so hack it back in with a test.
1. https://twitter.com/archeronl/status/745202118332657664
> cmd/gb: restore "all" alias

- cmd/gb/depfile.go
- cmd/gb/depfile_test.go
- cmd/gb/main.go
- context.go
Updates #536
- Adds support for reading `$PROJECT/depfile`
- Depfile entries are added to import list _after_ `$PROJECT/vendor`
TODO:
at the moment).
> feature: add depfile support

- cmd/gb/info.go
- context.go
- install_test.go
- package_test.go
- project.go
The source directories of a gb project never change, they are always
`$PROJECT/src` and `$PROJECT/vendor/src`. This method existed only for the
stale tests which needed to redirect the project's pkg directory to a
temporary location while keeping source in a known location.
> remove Project.Srcdirs() method

- context.go
- install_test.go
- resolver.go
When resolving packages they should be done so in an order that matches
the expected search order. First we look in GOROOT, if that misses, then
we look in $PROJECT/src, then if that fails we look in
$PROJECT/vendor/src.
Currently each of these importers has slightly different behaviour, that
will be fixed in a future PR. This current PR makes it possible to slip
another importer, provided by the depfile below the current ones, at the
lowest level.
> Refactor importers to not be a slice, but a stack.

- internal/vendor/manifest.go
- internal/vendor/manifest_test.go
Currently, `git-diff` command suggests "No newline at end of file".
And if edit `vendor/manifest` file uses any editor such as vim, will add newline to the end of file.
So meaningless commit diff will create.
However, this change is adding a new line to all of the manifest files of until now, so also will create meaningless commit diff.
If it normal behavior, please ignore it.
> internal/vendor: Add newline to end of file

- cmd/gb-vendor/fetch.go
- internal/vendor/depset.go
Fixes #635
golang/go#16333 renamed $GOROOT/src/vendor/golang.org to
$GOROOT/src/vendor/golang_org. This solved a nasty problem where code in
GOROOT would shadow any other copy of the net/http2 library, but meant
that gb vendor could no longer resolve the package and try to fetch it
(even if that was pointless).
To solve this, include $GOROOT/src/vendor in the set of search paths so
that golang_org/net/http/... is always found (if present).
I'll add a test for this in the integration test repo.
> cmd/gb-vendor: search $GOROOT/src/vendor when resolving recursive deps

- internal/vendor/discovery.go
- internal/vendor/imports_test.go
Addressing #642, port two changes from the upstream basis for the "vendor fetch" remote import path parser:
- [Go change 14482](https://go-review.googlesource.com/#/c/14482)  
_cmd/go: use RawToken to parse remote package metadata_
- [Go change 18051](https://go-review.googlesource.com/#/c/18051)  
_cmd/go: ignore XML errors after Go <meta> tags_
The first allows "vendor fetch" to accept a server response that matches the "go help importpath" documentation literally, providing solely a "meta" start tag as the entire document. More broadly, it accepts XML documents with improperly nested or even missing elements.
The latter allows "vendor fetch" to accept responses that contain invalid XML encountered after having read at least one "meta" start tag successfully, here the invalidity being …
> cmd/vendor: ignore invalid XML after <meta> tag

- cgo.go
Basically a copy of golang/go@b80b098bc523871d0657f8f68ed71882558f557f.
> Add check to see if gcc supports -no-pie. (#607)

- cmd/gb-vendor/delete.go
Previously, `gb vendor --all a b` would just delete all vendored
packages.
Closes #646
> Error when multiple paths are passed with --all

- cmd/gb-vendor/restore.go
I know this doesn't have a specific issue, but I figured it might be worth submitting a PR for. I found when building my project in CI, running `gb vendor restore` is the longest part.
Let me know if there are any glaring issues.
> Restore in parallel

- context.go
- depfile.go
- internal/importer/build_test.go
- internal/importer/importer.go
- internal/importer/importer_test.go
Part of the plan to replace internal/importer with go/build
> internal/importer: replace importer.Context with go/build.Context

- build.go
GoFiles in gb come in two kinds.
1. relative to pkg.Dir
2. absolute
In this case the work to absify then relify the path is a noop, which is
further proven by removing it.
> Remove filepath.Rel code from gc helper.

- cmd/gb-vendor/restore.go
For projects with a lot of dependencies, `gb vendor restore` won't work all the time and fail silently.
This makes pulling them more manageable and more resilient.
Closes #698
> Add semaphore to `gb vendor restore`

- package.go
Go 1.9 adds a few more internal packages that are implemented with
//go:linkname.
> gb: Annotate internal/poll as having external files

- build.go
- cmd/gb/gb_test.go
- goversion12.go
- goversion13.go
- goversion14.go
- goversion15.go
- goversion16.go
- goversion17.go
- goversion18.go
Fixes #707
Go 1.8 split out some parts of the testing package into
testing/internal/testdeps. This is an implicit dependency that needs to
be part of the dep graph to ensure if the runtime is stale, eg, when
cross compiling, it is rebuilt.
> gb: add testing/internal/testdeps as an extra dependency

- build.go
- cgo.go
- cmd/gb/gb_test.go
- gc.go
- goversion18.go
- internal/version/version12.go
- internal/version/version13.go
- internal/version/version14.go
- internal/version/version15.go
- internal/version/version16.go
- internal/version/version17.go
- internal/version/version18.go
- test/goversion12_test.go
- test/goversion13_test.go
- test/goversion14_test.go
- test/goversion15_test.go
- test/goversion16_test.go
- test/goversion17_test.go
- test/test_test.go
Introduce an internal package, internal/version to hold the Go version
constant. This probably won't matter after 0.5 drops support for Go 1.7
and earlier, but this refactoring makes it clear that the constant is
defined in one place, so we can delete it in one place.
> internal/version: introduce version package for constant

- cmd/gb/gb_test.go
- test/test.go
With a project layout like this:
```
.
└── src
└── proj
├── a
│   ├── a.cpp
│   ├── a.go
│   └── a.h
└── main.go
```
the `test` command will give a linker error when processing the `a` directory. This is because the `.cpp` files are not added to the test package. This change adds the `.cpp` files to the test package.
> Add CXXFiles to TestPackage

- .appveyor.yml
- .travis.yml
- cgo.go
- cmd/gb/gb_test.go
- gc.go
- internal/version/version12.go
- internal/version/version13.go
- internal/version/version14.go
- internal/version/version15.go
The minimum version is Go 1.6 because that is what appengine supports.
> gb: remove support for Go 1.5 and earlier
