cmd/env.go
cmd/gb-list/main.go
cmd/gb/main.go

Wrong path had been passed. In ImportPaths function it is clear that second argument is cwd.

fix gb-list behaviour inside src/%packagename

---

build.go
cmd/gb/build.go
cmd/gb/main.go
context.go
gb.go
gc.go
test_test.go
testdata/src/ldflags/ldflags.go
testdata/src/ldflags/ldflags_test.go
toolchain_test.go

Add support for -ldflags to build and test

---

cmd/cmd.go
cmd/gb/main.go
gc.go
gc14.go
gc15.go

Handle Go 1.4 and Go 1.5 toolchains independently

---

cgo.go
cgo14.go
cgo15.go
defaultcc.go
defaultcc_bsd.go

cgo: support default compiler on various operating systems

---

cgo.go
cgo14.go
cgo15.go
context.go
gc.go
gc14.go
gc15.go

Respect cgo: LDFLAGS

---

cgo.go

Fixes #111 
Fixes #107 
Fixes #112 
Fixes #118

Fix cgo builds on darwin (and clang)

---

cmd/gb-vendor/vendor/manifest.go

WriteManifest removes Manifest if there are 0 dependencies

---

cmd/cmd.go
cmd/gb-list/main.go
cmd/gb-vendor/delete.go
cmd/gb-vendor/fetch.go
cmd/gb-vendor/main.go
cmd/gb-vendor/update.go
cmd/gb/build.go
cmd/gb/env.go
cmd/gb/generate.go
cmd/gb/main.go
cmd/gb/plugin.go
cmd/gb/test.go

Fixes #142 
**Note:** Had to delete previous PR, because I commited it under wrong email...

Fixed random order of commands in usage message

---

cmd/gb/main.go
cmd/path.go
cmd/path_test.go

Fix for gb test with a symlink in the project path

---

cmd/gb-vendor/vendor/repo.go
cmd/gb-vendor/vendor/repo_test.go

cmd/gb-vendor/vendor: add support for launchpad and bzr

---

cmd/gb-vendor/vendor/repo.go

Git (1.8.3.1) on centos/rhel 7 doesn't support -C
Specify the working directory when executing git instead of using -C

Support older versions of git (gb-vendor)

---

cmd/gb-vendor/fetch.go
cmd/gb-vendor/vendor/manifest.go

Fixes #187 
Fetch won't clone the repository if it already exists.

Vendor fetch fix #187

---

cmd/gb-vendor/vendor/repo.go
cmd/gb-vendor/vendor/repo_test.go

cmd/gb-vendor/vendor: add support for repo.com/path.git format

---

cgo.go
cgo14.go
cgo15.go
gc15.go

Super early support for #cgo ldflags and pkg-config
Update #121
Update #162 (untested)
Update #167 (for go-sqlite3)

Initial pkg-config support

---

cmd/gb-vendor/update.go

Fixed bug that was found thanks to @dcarney's PR (#206) and refactored code.

Fixed and refactored update

---

cmd/gb-vendor/vendor/repo.go
cmd/gb-vendor/vendor/repo_test.go

cmd/gb-vendor/vendor: add support for code.google.com repos

---

cmd/gb-vendor/alldocs.go
cmd/gb-vendor/update.go

cmd/gb-vendor: update the long desc on the udpate subcommand

---

cmd/gb-vendor/update.go

Write manifest after each update.

---

cmd/gb-vendor/delete.go
cmd/gb-vendor/purge.go
cmd/gb-vendor/update.go
cmd/gb-vendor/vendor/copy.go
cmd/gb-vendor/vendor/remove.go
cmd/gb-vendor/vendor/repo.go

Windows: Make sure all files are writable before deleting a git clone.

---

cmd/gb-vendor/vendor/imports.go
cmd/gb-vendor/vendor/imports_test.go

cmd/gb-vendor/imports: fix import metadata parsing bugs

---

cmd/gb-vendor/vendor/depset.go

Fixes #245
When walking windows paths, convert the constructed directory to a
unix style import path so it matches FindMissing later on.

cmd/gb-vendor/vendor: fix windows path handling

---

cmd/gb-vendor/vendor/manifest.go

Prior to this change, any time you ran `gb vendor update $dependency` the dependency in question would be moved to the bottom of the manifest, regardless of any other changes. This behavior also happened when adding and removing dependencies.
This led to a noisy diff where it was difficult to easily see whether a commit hash changed or if the dependency moved etc.
This change alphabetically sorts dependencies within the manifest file, thus making the git diff of revision changes, additions, and removals much cleaner looking and easier to understand.

gb-vendor: Order dependencies in manifest file consistently

---

cmd/gb-vendor/vendor/repo.go

cmd/gb-vendor/vendor: add support for ssh:// git repos

---

cmd/gb-vendor/main.go

gb vendor needs the new syntax for NewProject to work.

Fix vendor introduced with #275

---

cmd/gb-vendor/main.go
cmd/gb-vendor/restore.go

Restore dependencies from the manifest file.
In relation to #175

Added restore to gb-vendor

---

cgo.go
cgo14.go
cgo15.go
wercker.yml

Improve support for cgo cflags and ldflags variables via pkg-config
Fixes #121

gb: better pkg-config support

---

cgo.go
cgo14.go
cgo15.go
wercker.yml

Fixes handling of cflags returned by pkg-config.
Replaces #303 
Fixes #114

Properly handle cflags presented from pkg-config

---

cgo.go
context.go
gb.go
gc.go
gc14.go
gc15.go
package.go

Refactor go{host,target},{os,arch} from gcToolchain to Context

---

cgo.go

Remove hard-coded -m64 references

---

cgo.go

* Reuse for cgo14 and cgo15
* Handle g++ and CPP/CXX flags

Refactor rungcc1 into shared method

---

cgo.go

Do not pass --build-id=none unless cc == clang

---

README.md
cgo.go
context.go
gc.go
package_test.go

Context refactor

---

context.go

Fixes bug introduced during recent context refactor in commit https://github.com/constabulary/gb/commit/4097af980ccf60c79b4c8350369192982f744bad.

Fix transposed context values.

---

gb.go
vendor/copy.go

Close target files after copy.

---

vendor/imports.go
vendor/imports_test.go

Improve the hint when gb failed to fetch the vendor package.

---

cgo.go
cmd/test_test.go
defaultcc.go
defaultcc_bsd.go
gc.go

cgo: support cgo packages that use c++

---

build.go
build_test.go
package_test.go

`package main` and a package called `main` is a subtle thing ...

Add pkgname unit test, fix latent bug

---

cmd/path.go
cmd/test_test.go

Fix infinite loop and wrong "Separator" issues for windows

---

vendor/path.go
vendor/path_test.go

vendor: handle error if root dir is missing

---

vendor/imports.go
vendor/imports_test.go

vendor: give better error when fetch fails on insecure report import

---

build.go
cmd/test.go
cmd/test_test.go

cmd: generate correct suffix for windows test binaries

---

build.go
build_test.go
package.go
package_test.go

Fix Binfile for all permutations of GOOS/GOARCH/Tags

---

action_test.go
build.go
cgo.go
cmd/gb/alldocs.go
cmd/test.go
executor.go
executor_test.go
gb.go

- Remove Task interface
- Rename Action.Task to Action.Run

Action Refactor

---

build.go
cmd/test.go

Build output is now printed by the final build action.
Test output is handled by the run action.

Handle build/test output better

---

gc.go

Reverts constabulary/gb#421
Mistake

Revert "Modify error paths to be relative to the working directory"

---

cmd/gb/test.go
context.go
resolve.go
test/resolve.go
test/test_test.go

Remove the nasty wart on the side of gb.Context.

Remove ResolvePackageWithTests

---

.travis.yml

Improve the fix for bitbucket.org hosts

---

gc.go

Fixes #445
Fixes #65
Rather than writing the linking the final binary directly, link
to a temporary file in the same directory, then rename atomically.
This should also fix the problem where the binary file is busy on
windows.

Don't write corrupt binary if linker is interrupted.

---

cmd/gb/gb_test.go
cmd/gb/info.go

Add functional test helper adapted from cmd/go tests.

cmd/gb: add func tests

---

cmd/gb/gb_test.go
cmd/gb/help.go
cmd/gb/main.go
cmd/gb/test.go
cmd/path.go
cmd/path_test.go

Finally solve the leaking files in /tmp problem.
TODO:

cmd/gb: finally stop leaking context.Workdir into /tmp

---

cmd/gb/gb_test.go
cmd/gb/testflag.go
cmd/gb/testflag_test.go
test/test.go

cmd/gb: fix additional flags passed to gb test

---

cmd/gb/gb_test.go

Update #481
Added some basic tests for `gb list`.

cmd/gb: add gb list tests

---

cmd/gb/gb_test.go

cmd/gb: added check for issue 416

---

cmd/gb/gb_test.go

cmd/gb: add test for issue 492

---

cmd/gb/gb_test.go

Added a test for issue 515

---

context.go
importer/build.go
importer/importer.go
importer/importer_test.go
package.go
package_test.go

Remove Package.Standard and let the embedded importer.Package.Standard field bubble up.

Remove Package.Standard

---

build.go
build_test.go
context.go
install.go
package.go
package_test.go
test/test.go

At one time I thought that there would be a lot of scopes, I was wrong.

Refactor Package.TestScope

---

build.go
build_test.go
cmd/gb/build.go
cmd/gb/test.go
context.go
install_test.go
package_test.go
test/test_test.go

Context.SkipInstall was backwards, it should be Context.Install and
defaults to _off_.

Refactor Context.SkipInstall

---

cmd/env.go
cmd/env_test.go
cmd/gb/doc.go
cmd/gb/env.go
cmd/gb/generate.go
cmd/gb/main.go

This reverts commit d1b0828fa7dda68b82fddcc5c320f45466a94de2.
/cc @psg-luna

Revert "cmd/gb: move env.go to cmd/gb"

---

context.go
example_test.go
package.go
package_test.go
test/test.go

Remove the panic from NewPackage/newPackage.

NewPackage returns error

---

cmd/gb/gb_test.go
context.go
context_test.go

Fixes #505
Only packages matching $PROJECT/src/... will match package arguments or globs.

Only match package from $PROJECT/src

---

cmd/gb/import.go
cmd/gb/import_test.go
context.go
context_test.go

Handle error from matchPackages.

---

cmd/gb/gb_test.go

Fixes #550
This change improves the output of missing package error, and a test
to assert it.
The rest of the improvements will come in #439.

Report better error when package is missing

---

vendor/repo_test.go

Fixes #594
Seeya code.google.com

vendor: remove code.google.com references

---

cmd/gb/alldocs.go
cmd/gb/build.go

cmd/gb: remove stale -q flag in documentation

---

cmd/gb/gb_test.go

Fixes #530
Add a test case for issue #530

cmd/gb: add test for issue 530

---

cmd/gb-vendor/restore.go
cmd/gb-vendor/update.go

Reverts constabulary/gb#586
This was a mistake. On inspection I don't think this change does anything and there is no test to demonstrate the fix.

Revert "Fix problem with private repositories"

---

appveyor.yml
build.go
cgo.go
cmd/cmd.go
cmd/gb-vendor/delete.go
cmd/gb-vendor/fetch.go
cmd/gb-vendor/list.go
cmd/gb-vendor/purge.go
cmd/gb-vendor/restore.go
cmd/gb-vendor/update.go
cmd/gb/build.go
cmd/gb/internal/depfile/depfile.go
cmd/gb/list.go
cmd/gb/plugin.go
cmd/gb/testflag.go
cmd/path.go
context.go
executor.go
gc.go
internal/fileutils/fileutils.go
internal/importer/build.go
internal/importer/pkg.go
internal/importer/util.go
internal/vendor/depset.go
internal/vendor/discovery.go
internal/vendor/imports.go
internal/vendor/manifest.go
package.go
test/test.go

First pass at converting from `errors` and `fmt` to `pkg/errors`

Use pkg/errors

---

cmd/gb/depfile_test.go
depfile.go

Add a new depfile key, `tag` which is an unadorned github release tag.

cmd/gb: add tag key to depfile

---

cgo.go
cmd/gb/internal/match/match.go
executor_test.go
gb_test.go
gc.go
internal/untar/untar.go

https://goreportcard.com/report/github.com/constabulary/gb

Cleanup go vet warnings

---

cgo.go
cmd/gb/internal/match/match.go
executor_test.go
gb_test.go
gc.go
internal/untar/untar.go

Revert "Cleanup go vet warnings"

---

cmd/env.go
cmd/gb/build.go
cmd/gb/gb_test.go
cmd/gb/plugin.go
cmd/gb/test.go
context.go
executor_test.go
internal/depfile/depfile.go
internal/fileutils/fileutils.go

https://goreportcard.com/report/github.com/constabulary/gb

Cleanup goreportcard warnings

---

cmd/gb-vendor/alldocs.go
cmd/gb-vendor/restore.go

Clean up parallel restore logic.

cmd/gb-vendor: clean up parallel restore

---

cmd/gb/main.go

Variables for flags and things are better defined inside main().

Remove a bunch of package level variables
